### ISSUE TITLE
mismatch between part 1 blog and this repo

### ISSUE THREAD

**Issue by erlebach** [T-DevH/llm_finetune_nemo#1]
I am reading part 1 of your upcoming series, which sounds great. I have noticed discrepencies between the blog and the repo. For example, I can't even find the yaml file that you reference in the blog: 
```yaml
model:
  model_name: "gpt-345m"
  pretrained: true
  peft:
    adapter_tuning:
      enabled: true
      adapter_dim: 64
      type: "parallel_adapter"
```
So was the blog illustrative, or should I expect that the blog describes the repo as it is layed out. Thanks.
